project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /src/TEdit/Properties/Language.resx
    translation: /src/TEdit/Properties/Language.%locale%.resx

languages_mapping:
  locale:
    zh-CN: zh-Hans
    zh-TW: zh-Hant
