//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TEdit.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal Left.
        /// </summary>
        public static string BrushShape_Left {
            get {
                return ResourceManager.GetString("BrushShape_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal Right.
        /// </summary>
        public static string BrushShape_Right {
            get {
                return ResourceManager.GetString("BrushShape_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string BrushShape_Round {
            get {
                return ResourceManager.GetString("BrushShape_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string BrushShape_Square {
            get {
                return ResourceManager.GetString("BrushShape_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not appear to contain Terraria Content.
        ///Press retry to pick a new folder or cancel to use {0} as your terraria path..
        /// </summary>
        public static string dialog_error_terriaria_folder_message {
            get {
                return ResourceManager.GetString("dialog_error_terriaria_folder_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terraria Content not Found.
        /// </summary>
        public static string dialog_error_terriaria_folder_title {
            get {
                return ResourceManager.GetString("dialog_error_terriaria_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string editor_tabs_analysis {
            get {
                return ResourceManager.GetString("editor_tabs_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string editor_tabs_clipboard {
            get {
                return ResourceManager.GetString("editor_tabs_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Data.
        /// </summary>
        public static string editor_tabs_npc {
            get {
                return ResourceManager.GetString("editor_tabs_npc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Tiles.
        /// </summary>
        public static string editor_tabs_special {
            get {
                return ResourceManager.GetString("editor_tabs_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites.
        /// </summary>
        public static string editor_tabs_sprites {
            get {
                return ResourceManager.GetString("editor_tabs_sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally.
        /// </summary>
        public static string editor_tabs_tally {
            get {
                return ResourceManager.GetString("editor_tabs_tally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Entities.
        /// </summary>
        public static string editor_tabs_tileentities {
            get {
                return ResourceManager.GetString("editor_tabs_tileentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Properties.
        /// </summary>
        public static string editor_tabs_worldproperties {
            get {
                return ResourceManager.GetString("editor_tabs_worldproperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string editor_utilities_label {
            get {
                return ResourceManager.GetString("editor_utilities_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy TEdit? Support Us!.
        /// </summary>
        public static string global_enjoytedit {
            get {
                return ResourceManager.GetString("global_enjoytedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string menu_edit {
            get {
                return ResourceManager.GetString("menu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string menu_edit_copy {
            get {
                return ResourceManager.GetString("menu_edit_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selection.
        /// </summary>
        public static string menu_edit_delete {
            get {
                return ResourceManager.GetString("menu_edit_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string menu_edit_paste {
            get {
                return ResourceManager.GetString("menu_edit_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string menu_edit_redo {
            get {
                return ResourceManager.GetString("menu_edit_redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string menu_edit_undo {
            get {
                return ResourceManager.GetString("menu_edit_undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string menu_file {
            get {
                return ResourceManager.GetString("menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Autosave.
        /// </summary>
        public static string menu_file_autosave {
            get {
                return ResourceManager.GetString("menu_file_autosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates on Startup.
        /// </summary>
        public static string menu_file_autoupdate {
            get {
                return ResourceManager.GetString("menu_file_autoupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string menu_file_exit {
            get {
                return ResourceManager.GetString("menu_file_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string menu_file_new {
            get {
                return ResourceManager.GetString("menu_file_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string menu_file_open {
            get {
                return ResourceManager.GetString("menu_file_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string menu_file_save {
            get {
                return ResourceManager.GetString("menu_file_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string menu_file_saveas {
            get {
                return ResourceManager.GetString("menu_file_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates Now.
        /// </summary>
        public static string menu_file_update {
            get {
                return ResourceManager.GetString("menu_file_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menu_help_about {
            get {
                return ResourceManager.GetString("menu_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log File.
        /// </summary>
        public static string menu_help_log {
            get {
                return ResourceManager.GetString("menu_help_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Settings.xml.
        /// </summary>
        public static string menu_help_settings {
            get {
                return ResourceManager.GetString("menu_help_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string menu_help_update {
            get {
                return ResourceManager.GetString("menu_help_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string menu_help_wiki {
            get {
                return ResourceManager.GetString("menu_help_wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string menu_layers {
            get {
                return ResourceManager.GetString("menu_layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuators.
        /// </summary>
        public static string menu_layers_actuators {
            get {
                return ResourceManager.GetString("menu_layers_actuators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Grid.
        /// </summary>
        public static string menu_layers_grid {
            get {
                return ResourceManager.GetString("menu_layers_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquids.
        /// </summary>
        public static string menu_layers_liquid {
            get {
                return ResourceManager.GetString("menu_layers_liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points of Interest.
        /// </summary>
        public static string menu_layers_points {
            get {
                return ResourceManager.GetString("menu_layers_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures.
        /// </summary>
        public static string menu_layers_textures {
            get {
                return ResourceManager.GetString("menu_layers_textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string menu_layers_tiles {
            get {
                return ResourceManager.GetString("menu_layers_tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls.
        /// </summary>
        public static string menu_layers_walls {
            get {
                return ResourceManager.GetString("menu_layers_walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Wire.
        /// </summary>
        public static string menu_layers_wire_blue {
            get {
                return ResourceManager.GetString("menu_layers_wire_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Wire.
        /// </summary>
        public static string menu_layers_wire_green {
            get {
                return ResourceManager.GetString("menu_layers_wire_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Wire.
        /// </summary>
        public static string menu_layers_wire_red {
            get {
                return ResourceManager.GetString("menu_layers_wire_red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Wire.
        /// </summary>
        public static string menu_layers_wire_yellow {
            get {
                return ResourceManager.GetString("menu_layers_wire_yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string menu_plugins {
            get {
                return ResourceManager.GetString("menu_plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string menu_toolbar_zoom_in {
            get {
                return ResourceManager.GetString("menu_toolbar_zoom_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string menu_toolbar_zoom_out {
            get {
                return ResourceManager.GetString("menu_toolbar_zoom_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string statusbar_extra_label {
            get {
                return ResourceManager.GetString("statusbar_extra_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        public static string statusbar_frame_label {
            get {
                return ResourceManager.GetString("statusbar_frame_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.
        /// </summary>
        public static string statusbar_paint_label {
            get {
                return ResourceManager.GetString("statusbar_paint_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string statusbar_position_label {
            get {
                return ResourceManager.GetString("statusbar_position_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string statusbar_selection_label {
            get {
                return ResourceManager.GetString("statusbar_selection_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string statusbar_tile_label {
            get {
                return ResourceManager.GetString("statusbar_tile_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        public static string statusbar_wall_label {
            get {
                return ResourceManager.GetString("statusbar_wall_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        public static string tool_arrow_title {
            get {
                return ResourceManager.GetString("tool_arrow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string tool_brush_height_label {
            get {
                return ResourceManager.GetString("tool_brush_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Width and Height.
        /// </summary>
        public static string tool_brush_lock_ratio_tooltip {
            get {
                return ResourceManager.GetString("tool_brush_lock_ratio_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string tool_brush_outline_thickness_label {
            get {
                return ResourceManager.GetString("tool_brush_outline_thickness_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Draw Outline (room).
        /// </summary>
        public static string tool_brush_outline_tooltip {
            get {
                return ResourceManager.GetString("tool_brush_outline_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string tool_brush_shape_label {
            get {
                return ResourceManager.GetString("tool_brush_shape_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        public static string tool_brush_title {
            get {
                return ResourceManager.GetString("tool_brush_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string tool_brush_width_label {
            get {
                return ResourceManager.GetString("tool_brush_width_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string tool_fill_title {
            get {
                return ResourceManager.GetString("tool_fill_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biome Morph.
        /// </summary>
        public static string tool_morph_title {
            get {
                return ResourceManager.GetString("tool_morph_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string tool_paste_title {
            get {
                return ResourceManager.GetString("tool_paste_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencil.
        /// </summary>
        public static string tool_pencil_title {
            get {
                return ResourceManager.GetString("tool_pencil_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker - select tile color.
        /// </summary>
        public static string tool_picker_title {
            get {
                return ResourceManager.GetString("tool_picker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Interest Points.
        /// </summary>
        public static string tool_point_title {
            get {
                return ResourceManager.GetString("tool_point_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite Placer (OLD).
        /// </summary>
        public static string tool_sprite_title {
            get {
                return ResourceManager.GetString("tool_sprite_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite Placer.
        /// </summary>
        public static string tool_sprite2_title {
            get {
                return ResourceManager.GetString("tool_sprite2_title", resourceCulture);
            }
        }
    }
}
